In [11]:
fp = '/home/aryan/Desktop/train.csv'
import pandas as p
import numpy as n
import matplotlib.pyplot as pt
%matplotlib inline

In [21]:
df = p.read_csv(fp)
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [22]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726   
std       1.112799    30.202904     20.645407   181.066207   456.098091   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000   

           ...         WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count      ...        1460.000000  1460.000000    1460.000000  1460.000000   
mean       ...          94.244521    46.660274      21.954110     3.409589   
std        ...         125.338794    66.256028      61.119149    29.317331   
min        ...           0.000000     0.000000       0.000000     0.000000   
25%        ...           0.000000     0.000000       0.000000     0.000000   
50%        ...           0.000000    25.000000       0.000000     0.000000   
75%        ...         168.000000    68.000000       0.000000     0.000000   
max        ...         857.000000   547.000000     552.000000   508.000000   

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000   
mean     15.060959     2.758904     43.489041     6.321918  2007.815753   
std      55.757415    40.177307    496.123024     2.703626     1.328095   
min       0.000000     0.000000      0.000000     1.000000  2006.000000   
25%       0.000000     0.000000      0.000000     5.000000  2007.000000   
50%       0.000000     0.000000      0.000000     6.000000  2008.000000   
75%       0.000000     0.000000      0.000000     8.000000  2009.000000   
max     480.000000   738.000000  15500.000000    12.000000  2010.000000   

           SalePrice  
count    1460.000000  
mean   180921.195890  
std     79442.502883  
min     34900.000000  
25%    129975.000000  
50%    163000.000000  
75%    214000.000000  
max    755000.000000  

[8 rows x 38 columns]

In [38]:
df.agg(['min','max','mean'])

Id  MSSubClass MSZoning        LotArea Street LotShape LandContour  \
min      1.0    20.00000  C (all)    1300.000000   Grvl      IR1         Bnk   
max   1460.0   190.00000       RM  215245.000000   Pave      Reg         Lvl   
mean   730.5    56.89726      NaN   10516.828082    NaN      NaN         NaN   

     Utilities LotConfig LandSlope      ...      EnclosedPorch   3SsnPorch  \
min     AllPub    Corner       Gtl      ...            0.00000    0.000000   
max     NoSeWa    Inside       Sev      ...          552.00000  508.000000   
mean       NaN       NaN       NaN      ...           21.95411    3.409589   

     ScreenPorch    PoolArea       MiscVal     MoSold       YrSold  SaleType  \
min     0.000000    0.000000      0.000000   1.000000  2006.000000       COD   
max   480.000000  738.000000  15500.000000  12.000000  2010.000000        WD   
mean   15.060959    2.758904     43.489041   6.321918  2007.815753       NaN   

      SaleCondition     SalePrice  
min         Abnorml   34900.00000  
max         Partial  755000.00000  
mean            NaN  180921.19589  

[3 rows x 62 columns]

# Data Cleaning performed

In [35]:
df = df.dropna(axis='columns')

In [37]:
df.describe()

Id   MSSubClass        LotArea  OverallQual  OverallCond  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean    730.500000    56.897260   10516.828082     6.099315     5.575342   
std     421.610009    42.300571    9981.264932     1.382997     1.112799   
min       1.000000    20.000000    1300.000000     1.000000     1.000000   
25%     365.750000    20.000000    7553.500000     5.000000     5.000000   
50%     730.500000    50.000000    9478.500000     6.000000     5.000000   
75%    1095.250000    70.000000   11601.500000     7.000000     6.000000   
max    1460.000000   190.000000  215245.000000    10.000000     9.000000   

         YearBuilt  YearRemodAdd   BsmtFinSF1   BsmtFinSF2    BsmtUnfSF  \
count  1460.000000   1460.000000  1460.000000  1460.000000  1460.000000   
mean   1971.267808   1984.865753   443.639726    46.549315   567.240411   
std      30.202904     20.645407   456.098091   161.319273   441.866955   
min    1872.000000   1950.000000     0.000000     0.000000     0.000000   
25%    1954.000000   1967.000000     0.000000     0.000000   223.000000   
50%    1973.000000   1994.000000   383.500000     0.000000   477.500000   
75%    2000.000000   2004.000000   712.250000     0.000000   808.000000   
max    2010.000000   2010.000000  5644.000000  1474.000000  2336.000000   

           ...         WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count      ...        1460.000000  1460.000000    1460.000000  1460.000000   
mean       ...          94.244521    46.660274      21.954110     3.409589   
std        ...         125.338794    66.256028      61.119149    29.317331   
min        ...           0.000000     0.000000       0.000000     0.000000   
25%        ...           0.000000     0.000000       0.000000     0.000000   
50%        ...           0.000000    25.000000       0.000000     0.000000   
75%        ...         168.000000    68.000000       0.000000     0.000000   
max        ...         857.000000   547.000000     552.000000   508.000000   

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000   
mean     15.060959     2.758904     43.489041     6.321918  2007.815753   
std      55.757415    40.177307    496.123024     2.703626     1.328095   
min       0.000000     0.000000      0.000000     1.000000  2006.000000   
25%       0.000000     0.000000      0.000000     5.000000  2007.000000   
50%       0.000000     0.000000      0.000000     6.000000  2008.000000   
75%       0.000000     0.000000      0.000000     8.000000  2009.000000   
max     480.000000   738.000000  15500.000000    12.000000  2010.000000   

           SalePrice  
count    1460.000000  
mean   180921.195890  
std     79442.502883  
min     34900.000000  
25%    129975.000000  
50%    163000.000000  
75%    214000.000000  
max    755000.000000  

[8 rows x 35 columns]

In [39]:
df.agg(['min','max','mean'])

Id  MSSubClass MSZoning        LotArea Street LotShape LandContour  \
min      1.0    20.00000  C (all)    1300.000000   Grvl      IR1         Bnk   
max   1460.0   190.00000       RM  215245.000000   Pave      Reg         Lvl   
mean   730.5    56.89726      NaN   10516.828082    NaN      NaN         NaN   

     Utilities LotConfig LandSlope      ...      EnclosedPorch   3SsnPorch  \
min     AllPub    Corner       Gtl      ...            0.00000    0.000000   
max     NoSeWa    Inside       Sev      ...          552.00000  508.000000   
mean       NaN       NaN       NaN      ...           21.95411    3.409589   

     ScreenPorch    PoolArea       MiscVal     MoSold       YrSold  SaleType  \
min     0.000000    0.000000      0.000000   1.000000  2006.000000       COD   
max   480.000000  738.000000  15500.000000  12.000000  2010.000000        WD   
mean   15.060959    2.758904     43.489041   6.321918  2007.815753       NaN   

      SaleCondition     SalePrice  
min         Abnorml   34900.00000  
max         Partial  755000.00000  
mean            NaN  180921.19589  

[3 rows x 62 columns]

In [66]:
df

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
1349  1350          70       RM     5250   Pave      Reg         Lvl   
1137  1138          50       RL     6342   Pave      Reg         Lvl   
747    748          70       RM    11700   Pave      IR1         Lvl   
304    305          75       RM    18386   Pave      Reg         Lvl   
1132  1133          70       RM     9900   Pave      Reg         Lvl   
630    631          70       RM     9000   Pave      Reg         Lvl   
991    992          70       RM    17671   Pave      Reg         Lvl   
106    107          30       RM    10800   Pave      Reg         Lvl   
1416  1417         190       RM    11340   Pave      Reg         Lvl   
945    946          50       RM     8820   Pave      Reg         Lvl   
716    717          70       RM    10800   Pave      Reg         Bnk   
185    186          75       RM    22950   Pave      IR2         Lvl   
1292  1293          70       RM     6600   Pave      Reg         Lvl   
583    584          75       RM    13500   Pave      Reg         Lvl   
809    810          75       RM     8100   Pave      Reg         Lvl   
711    712          50  C (all)     8712   Pave      Reg         HLS   
703    704         190       RM     7630   Pave      Reg         Lvl   
242    243          50       RM     5000   Pave      Reg         Lvl   
390    391          50       RL     8405   Pave      Reg         Lvl   
1186  1187         190       RL    10615   Pave      IR1         Bnk   
1062  1063         190       RM    13600   Pave      Reg         Lvl   
520    521         190       RL    10800   Pave      Reg         Lvl   
488    489         190       RL    10800   Pave      Reg         Lvl   
676    677          70       RM     9600   Pave      Reg         Lvl   
921    922          90       RL     8777   Pave      Reg         Lvl   
841    842          70       RM    10440   Pave      Reg         Lvl   
1393  1394         190       RM    10800   Pave      Reg         Lvl   
653    654          50       RM    10320   Pave      Reg         Lvl   
184    185          50       RL     7438   Pave      IR1         Lvl   
848    849          50       RL    45600   Pave      IR2         Bnk   
...    ...         ...      ...      ...    ...      ...         ...   
1166  1167          20       RL    10475   Pave      IR1         Lvl   
581    582          20       RL    12704   Pave      Reg         Lvl   
798    799          60       RL    13518   Pave      Reg         Lvl   
1316  1317          20       RL    10226   Pave      IR1         Lvl   
1298  1299          60       RL    63887   Pave      IR3         Bnk   
803    804          60       RL    13891   Pave      Reg         Lvl   
805    806          20       RL    12274   Pave      IR1         Lvl   
240    241          20       FV     9000   Pave      Reg         Lvl   
440    441          20       RL    15431   Pave      Reg         Lvl   
1058  1059          60       RL    11308   Pave      IR1         Lvl   
765    766          20       RL    14587   Pave      IR1         Lvl   
987    988          20       RL    10159   Pave      IR1         Lvl   
572    573          60       RL    13159   Pave      IR1         HLS   
460    461          60       FV     8004   Pave      IR1         Lvl   
1217  1218          20       FV     8640   Pave      Reg         Lvl   
819    820         120       RL     6371   Pave      IR1         Lvl   
507    508          20       FV     7862   Pave      IR1         Lvl   
914    915         160       FV     3000   Pave      Reg         Lvl   
103    104          20       RL    10402   Pave      IR1         Lvl   
644    645          20       FV     9187   Pave      Reg         Lvl   
212    213          60       FV     8640   Pave      Reg         Lvl   
412    413          20       FV     4403   Pave      IR2         Lvl   
211    212          20       RL    10420   Pave      Reg         Lvl   
87      88         160       FV     3951   Pave 

In [67]:
for i in df.columns:
    print(df[i].unique())

[1350 1138  748 ...  158  763  379]
[ 70  50  75  30 190  90  45  40  20  60  80  85 160 180 120]
['RM' 'RL' 'C (all)' 'RH' 'FV']
[ 5250  6342 11700 ... 12220 12003 11394]
['Pave' 'Grvl']
['Reg' 'IR1' 'IR2' 'IR3']
['Lvl' 'Bnk' 'HLS' 'Low']
['AllPub' 'NoSeWa']
['Inside' 'Corner' 'FR2' 'FR3' 'CulDSac']
['Gtl' 'Mod' 'Sev']
['OldTown' 'Sawyer' 'IDOTRR' 'Edwards' 'BrkSide' 'ClearCr' 'Crawfor'
 'SWISU' 'NAmes' 'SawyerW' 'Mitchel' 'Gilbert' 'Timber' 'NWAmes' 'CollgCr'
 'BrDale' 'MeadowV' 'Veenker' 'NPkVill' 'Blueste' 'StoneBr' 'NoRidge'
 'Somerst' 'Blmngtn' 'NridgHt']
['Norm' 'Feedr' 'Artery' 'RRAn' 'PosN' 'RRNn' 'RRAe' 'PosA' 'RRNe']
['Norm' 'PosA' 'Artery' 'Feedr' 'RRNn' 'RRAn' 'RRAe' 'PosN']
['1Fam' '2fmCon' 'Duplex' 'Twnhs' 'TwnhsE']
['2Story' '1.5Fin' '2.5Fin' '1Story' '2.5Unf' '1.5Unf' 'SLvl' 'SFoyer']
[ 8  5  7  6  4 10  3  2  1  9]
[5 8 7 9 4 6 2 3 1]
[1872 1875 1880 1882 1885 1890 1892 1893 1898 1900 1904 1905 1906 1908
 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 192

In [68]:
df = df.sort_values(by=['YearBuilt'])